print(1)# INI ADALAH SEBUAH ANGKA DAPAT DI BERI OPERASI MATEMATIKA

print(1.5) # JIKA INGIN MENULISKAN ANGKA DESIMAL MENGGUNAKAN (.) BUKAN (,) UNTUK PEULISANNYA

print("1") # INI ADALAH SEBUAH TEXT TIDAK DAPAT DI BERI OPERASI MATEMATIKA (*), (/), (+), (-)
