# ELSE BERFUNGSI UNTUK MEMBERIKAN HASIL YANG BERLAWANAN DENGAN ATRIBUT KONDISI IF
menang = False

if menang: # KONDISI DAPAT DI BUAT SEPERTI INI JIKA NILAI DARI VARIABLE BERTIPE DATA BOOLEAN
  print("Selamat")
else:
  print("Coba Lagi")