# FUNGSI RANGE MERUPAKAN UNTUK MEMUDAHKAN MENULIST DERETAN ANGKA DENGAN HANYA MENULISKAN BATAS AWAL DAN BATAS AKHIRNYA
# nomor = [1,2,3,4,5,6,7,8,9,10]

# PENULISAN CODE RANGE, SEMISAL BATAS AKHIR YANG SAYA MAU ADALAH 100 TAPI DI CODE HARUS DITAMBAH 1 (101) AGAR DAPAT MENGHASILKAN BATAS AKHIR 100
nomor = range(1,101)

for no in nomor:
  print(no)

# PENULISAN RANGE JUGA DAPAT DI MASUKAN PADA PERINTAH FOR
for nomor in range(1,101):
  print(nomor)